/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        neutral_0: "var(--color-neutral-0)",
        neutral_0_rgb: "var(--color-neutral-0-rgb)",
        neutral_1: "var(--color-neutral-1)",
        neutral_2: "var(--color-neutral-2)",
        neutral_3: "var(--color-neutral-3)",
        neutral_4: "var(--color-neutral-4)",
        neutral_5: "var(--color-neutral-5)",
        neutral_6: "var(--color-neutral-6)",
        neutral_7: "var(--color-neutral-7)",
        neutral_8: "var(--color-neutral-8)",
        neutral_4_rgb: "var(--color-neutral-8-rgb)",
        orange_1: "var(--color-orange-1)",
        orange_2: "var(--color-orange-2)",
        orange_3: "var(--color-orange-3)",
        orange_4: "var(--color-orange-4)",
        orange_5: "var(--color-orange-5)",
        orange_6: "var(--color-orange-6)",
        orange_7: "var(--color-orange-7)",
        red_1: "var(--color-red-1)",
        red_2: "var(--color-red-2)",
        red_3: "var(--color-red-3)",
        red_4: "var(--color-red-4)",
        red_5: "var(--color-red-5)",
        red_6: "var(--color-red-6)",
        red_7: "var(--color-red-7)",
        magenta_1: "var(--color-magenta-1)",
        magenta_2: "var(--color-magenta-2)",
        magenta_3: "var(--color-magenta-3)",
        magenta_4: "var(--color-magenta-4)",
        magenta_5: "var(--color-magenta-5)",
        magenta_6: "var(--color-magenta-6)",
        magenta_7: "var(--color-magenta-7)",
        blue_1: "var(--color-blue-1)",
        blue_2: "var(--color-blue-2)",
        blue_3: "var(--color-blue-3)",
        blue_4: "var(--color-blue-4)",
        blue_5: "var(--color-blue-5)",
        blue_6: "var(--color-blue-6)",
        blue_7: "var(--color-blue-7)",
        green_1: "var(--color-green-1)",
        green_2: "var(--color-green-2)",
        green_3: "var(--color-green-3)",
        green_4: "var(--color-green-4)",
        green_5: "var(--color-green-5)",
        green_6: "var(--color-green-6)",
        green_7: "var(--color-green-7)",
        yellow_1: "var(--color-yellow-1)",
        yellow_2: "var(--color-yellow-2)",
        yellow_3: "var(--color-yellow-3)",
        yellow_4: "var(--color-yellow-4)",
        yellow_5: "var(--color-yellow-5)",
        yellow_6: "var(--color-yellow-6)",
        yellow_7: "var(--color-yellow-7)",
        teal_1: "var(--color-teal-1)",
        teal_2: "var(--color-teal-2)",
        teal_3: "var(--color-teal-3)",
        teal_4: "var(--color-teal-4)",
        teal_5: "var(--color-teal-5)",
        teal_6: "var(--color-teal-6)",
        teal_7: "var(--color-teal-7)",
        lime_1: "var(--color-lime-1)",
        lime_2: "var(--color-lime-2)",
        lime_3: "var(--color-lime-3)",
        lime_4: "var(--color-lime-4)",
        lime_5: "var(--color-lime-5)",
        lime_6: "var(--color-lime-6)",
        lime_7: "var(--color-lime-7)",
        ai_solid_green_strong: "var(--color-ai-solid-green-strong)",
        ai_solid_green_subtle: "var(--color-ai-solid-green-subtle)",
        ai_solid_green_strong_dark: "var(--color-ai-solid-green-strong-dark)",
        
        ai_solid_blue_strong: "var(--color-ai-solid-blue-strong)",
        ai_solid_blue_subtle: "var(--color-ai-solid-blue-subtle)",
        ai_solid_blue_strong_dark: "var(--color-ai-solid-blue-strong-dark)",

        ai_solid_purple_strong: "var(--color-ai-solid-purple-strong)",
        ai_solid_purple_subtle: "var(--color-ai-solid-purple-subtle)",
        ai_solid_purple_strong_dark: "var(--color-ai-solid-purple-strong-dark)",

        ai_solid_red_strong: "var(--color-ai-solid-red-strong)",
        ai_solid_red_subtle: "var(--color-ai-solid-red-subtle)",
        ai_solid_red_strong_dark: "var(--color-ai-solid-red-strong-dark)",

        ai_solid_yellow_strong: "var(--color-ai-solid-yellow-strong)",
      },
    },
  },
  plugins: [],
}

